services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MarvinhersSql
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # 想连navicat可以加一个ports 
  web:
    image: marvinhers/ezsqql:latest
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db